default:
  FACEBOOK_APP_ID: 351962708876636
  FACEBOOK_APP_SERCRET: c786c478795284e63382a7ad25f1bc02
  FACEBOOK_APP_VERSION: 'v2.8'
  GOOGLE_APP_ID: AIzaSyABlEDCf4JOf4xWbFCL8B4d2_LaBwKyxMM
  GOOGLE_APP_SERCRET: YeNIMeyYIy_WET8UtvXTRJac
  TWITTER_CONSUMER_KEY: xbS4nTM6WNVBBdfXkYsDyVrFl
  TWITTER_CONSUMER_SECRET: twn3AOGRwChvPcFo5F1r68ngjjKv2fflxTrdEs5p9FWA8ZjeSq
  LINKEDIN_APP_ID: 818rqmnow8tg5b
  LINKEDIN_APP_SERCRET: QPWh8q4XNqlMntZu
development:
  FACEBOOK_APP_ID: 351962708876636
  FACEBOOK_APP_SERCRET: c786c478795284e63382a7ad25f1bc02
  FACEBOOK_APP_VERSION: 'v2.8'
  GOOGLE_APP_ID: AIzaSyDaH2UowQZWleYnH5u5_MIydey0kzTE9C4
  GOOGLE_APP_SERCRET: AIzaSyAcrHfpHGhfJcU-AU8nU5dFJzxMGwV4Nb0
  TWITTER_CONSUMER_KEY: xbS4nTM6WNVBBdfXkYsDyVrFl
  TWITTER_CONSUMER_SECRET: twn3AOGRwChvPcFo5F1r68ngjjKv2fflxTrdEs5p9FWA8ZjeSq
  LINKEDIN_APP_ID: 818rqmnow8tg5b
  LINKEDIN_APP_SERCRET: QPWh8q4XNqlMntZu
  RECAPTCHA_SITE_KEY: 6LfxdZ8UAAAAAKAr_66UFUcDks0dt60s8PT57_CO
  RECAPTCHA_SECRET_KEY: 6LfxdZ8UAAAAAGdrNGXukCIN9o5D9bh3U40iwCnI
production:
  FACEBOOK_APP_ID: 388569708390446
  FACEBOOK_APP_SERCRET: 6548dbdf05c814e82f752b62613111b4
  FACEBOOK_APP_VERSION: 'v2.8'
  GOOGLE_APP_ID: AIzaSyABlEDCf4JOf4xWbFCL8B4d2_LaBwKyxMM
  GOOGLE_APP_SERCRET: YeNIMeyYIy_WET8UtvXTRJac
  TWITTER_CONSUMER_KEY: xbS4nTM6WNVBBdfXkYsDyVrFl
  TWITTER_CONSUMER_SECRET: twn3AOGRwChvPcFo5F1r68ngjjKv2fflxTrdEs5p9FWA8ZjeSq
  LINKEDIN_APP_ID: 818rqmnow8tg5b
  LINKEDIN_APP_SERCRET: QPWh8q4XNqlMntZu
  RECAPTCHA_SITE_KEY: 6LerAqkUAAAAAM8PMnFPlBDGy4_d8Oj1L-RJUbjz
  RECAPTCHA_SECRET_KEY: 6LerAqkUAAAAABKCWRDf92qd90tUpqZDafot7u0O