default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  secure_auth: false
  database: educations
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default

testing:
  <<: *default

production:
  <<: *default
